### PR TITLE
Test against Doctrine 2.5 and PHP 7

### PR DESCRIPTION
**Pull request by nimasdj**

### CODE REVIEW

**Comment by nimasdj** [comment]
@stevelacey  It seems your recent change to tidy TestDate.php did damage the test! you need to change it back to what it was.

**Comment by nimasdj** [comment]
@stevelacey well see your mistake #159

**Comment by nimasdj** [comment]
@stevelacey I merged both DateTest.php fixing your mistake with missing ; on line 52 into this travis PR together,

**Comment by stevelacey** [comment]
@nimasdj ah yeah, thanks... I'll merge this now :disappointed_relieved:

**Comment by nimasdj** [comment]
failure of php7 and doctrine2.5 have nothing to do with testcase but this is because of your travis server and composer setup, please fix them and I believe php7 and doctrine2.5 testcase will work.

**Comment by stevelacey** [comment]
Doctrine 2.5 doesn't work cleanly, at the very least the PHP 5.3 + Doctrine 2.5 test case needs excluding as per #160 – I think there are other breaks too – IIRC they changed the column aliasing a bit so they come out different... which is a bit of a PITA given all of the hardcoded SQL assertions here :confused: either way I've merged PHP 7 and we can continue working on 2.5 in #160.

**Pull request merged**
