### PR TITLE
ADDED - Mysql DATE_SUB() Function

### PR DESCRIPTION
**Pull request by pnvasanth**
Check the changes and merge it.

### CODE REVIEW

**Comment by pnvasanth** [comment]
Hi, due to `composer self-update`  the unit tests got failed. 
@stevelacey Could you please check my PR and let me know your inputs?

**Comment by stevelacey** [comment]
@pnvasanth can you resolve the merge conflicts and I'll give this a look and make sure the test suite passes

**Comment by pnvasanth** [comment]
@stevelacey I have resolved the merge conflicts, could you please check it.

**Comment by stevelacey** [comment]
@pnvasanth looks good, thanks for your contribution :smile_cat:

**Pull request merged**
