### PR TITLE
Add MySQL BIT_COUNT() function

### PR DESCRIPTION
**Pull request by lstrojny**
See https://dev.mysql.com/doc/refman/5.7/en/bit-functions.html

### CODE REVIEW

**Comment by rapemer** [comment]
+1

**Comment by stevelacey** [comment]
@lstrojny :ok_hand: thanks for your contribution!

**Comment by lstrojny** [comment]
@stevelacey thank you very much for tagging. Care to release a v1.0.8?

**Comment by stevelacey** [comment]
@lstrojny done :smile_cat:

**Pull request merged**
