### PR TITLE
Add MySQL EXTRACT() support

### PR DESCRIPTION
**Pull request by fhriz**
Add MySQL function EXTRACT()

### CODE REVIEW

**Comment by stevelacey** [comment]
Sorry, I merged something ahead of this and now there are conflicts, can you fix?

**Comment by fhriz** [comment]
@stevelace I've done merging the conflicts.

**Comment by stevelacey** [comment]
@fhriz thanks for your contribution :smile:

**Comment by fhriz** [comment]
Hi @stevelacey 
Can I get a new release tag version for this merged? 

Thank you very much.

**Comment by stevelacey** [comment]
Yessir, `v1.0.15`

**Pull request merged**
