### PR TITLE
Support Doctrine 2.5

### PR DESCRIPTION
**Pull request by stevelacey**
@nimasdj thanks for submiting this, I merged #158 but it caused some problems which need resolving here before it can go in

### CODE REVIEW

**Comment by nimasdj** [comment]
@stevelacey welcome, but why is travis hanged?

**Comment by stevelacey** [comment]
@nimasdj I think it has a limit on concurrent builds, you can see the errors now, as I suspected, loads of differences with column aliases :confused: not sure how to tackle this really without breaking the tests against older versions – I'd like to aim for a better solution than lots of if statements

**Comment by nimasdj** [comment]
@stevelacey I tested FROM_UNIXTIME with doctrine2.5 and I see it is working fine! I can confirm functions itself have no problem with doctrine2.5, but these testcases have problem! This is why I hate PHPUnit/travis and I test everything on live production always!
Since I am sure functions are fine with doctrine2.5, with this test I am confortable that it will work with php7 too! :+1:

**Comment by stevelacey** [comment]
@nimasdj I am not going to use this medium to preach the benefits of automated tests – if you're blindly deploying to production and that's going well for you, then good for you, the rest of us live in the real world, unfortunately.

Any failures here are symptomatic of poorly written tests in this library, not of failings in PHPUnit – in fact, the real issue here is that we're assessing the effectiveness of the MySQL functions by asserting the SQL produced matches our expectations, which is a flimsy strategy in itself, especially when it falls apart because Doctrine doesn't expect you to care about field aliases.

**Pull request merged**
