### PR TITLE
Oracle - CEIL function

### PR DESCRIPTION
**Pull request by jeffersonbehling**

### CODE REVIEW

**Comment by stevelacey** [comment]
@jeffersonbehling Thanks for your contribution 🙂 Can you rebase it? And stick the complementary methods like FLOOR in? It'd be odd to offer CEIL and CEIL alone.

**Comment by jeffersonbehling** [comment]
Hello @stevelacey,
The FLOOR function has been created.

**Comment by stevelacey** [comment]
@jeffersonbehling thanks! Can you add some tests for them? Also what's the TO_CHAR stuff?

**Comment by jeffersonbehling** [comment]
@stevelacey 
I just created the tests for CEIL and FLOOR.
The modification I made in TO_CHAR refers to the third parameter that the function accepts, which is nls_numeric_characters.

**Comment by jeffersonbehling** [comment]
@stevelacey All right?

**Comment by stevelacey** [comment]
@jeffersonbehling looks good, I made some small amends, lastly, can you add a test for `TO_CHAR` with the new nls param? After that I think this is good to go 👍

**Comment by stevelacey** [comment]
Thanks for your contribution 🙂

**Pull request merged**
