### PR TITLE
Added support for the MySQL VARIANCE aggregate function.

### PR DESCRIPTION
**Pull request by maxolasersquad**

### CODE REVIEW

**Comment by stevelacey** [comment]
@maxolasersquad looks good, bonus points for the test! – Travis will be failing because you forgot to update the README to describe the new function, chuck that in and I'll go ahead and merge – thanks for your contribution! :D

**Comment by maxolasersquad** [comment]
Ok, didn't know to update the README. I've amended my commit and pushed.

**Comment by maxolasersquad** [comment]
The other test is now passing. However testing that variance works is failing. I'm not sure what other changes I should be making to get the test to pass. I have this version of DoctrineExtensions running in one of my projects and VARIANCE is working as expected, however the same config changes within this project do not seem to be working for the tests.

**Comment by stevelacey** [comment]
Appears you need to load `Variance` in tests/Query/MysqlTestCase.php.

Yes, this is dumb and I am sorry about that.

**Comment by maxolasersquad** [comment]
Awesome, all the tests are passing now. I'm working on the PR you requested. It will naturally create a merge conflict with this commit so will wait for it to be accepted to to a PR for it.

**Comment by stevelacey** [comment]
@maxolasersquad thanks for your contribution :smile:

**Pull request merged**
