### PR TITLE
PHP 8 Supports

### PR DESCRIPTION
**Pull request by palanisamy-emis**

### CODE REVIEW

**Comment by micter59** [comment]
I hope the maintainer will merge your PR, i'm waiting for this for a long time. Thanks !

**Comment by adrienfr** [comment]
@palanisamy-emis duplicate of recently merged https://github.com/beberlei/DoctrineExtensions/pull/380/files no?

**Comment by julienmiclo** [comment]
@adrienfr The #380 only add support for Oracle so maybe for Oracle but MySQL, PostgreSQL and SQLite no duplication.

**Comment by tarjei** [comment]
@adrienfr any news on getting out a new release here?

**Comment by adrienfr** [comment]
> @adrienfr any news on getting out a new release here?

I'm not a maintainer of this repo.

According to [this post](https://github.com/beberlei/DoctrineExtensions/pull/380#issuecomment-1162899265), a new release is not expected, project is not maintained anymore.

**Pull request closed without merging**
