### PR TITLE
MySQL: PERIOD_DIFF

### PR DESCRIPTION
**Pull request by eigan**
Hi, I needed this for a project. Its just a clone and simple modification of DateDiff :innocent:

### CODE REVIEW

**Comment by stevelacey** [comment]
@eigan tests fail... I looked but I don't entirely follow why given it looks like you did literally copy and paste this from `DATE_DIFF` – can you take a look, maybe you can work out why

**Comment by stevelacey** [comment]
@eigan looks like this might be cleared up by @maxolasersquad's work in #230 – so lets revisit this after that's merged, @ me if I don't get back to you, note this branch now conflicts with master so it will also need rebasing – thanks for your contribution!

**Comment by eigan** [comment]
I squashed/rebased my commits. Never done that before, sorry if I messed up something :no_mouth:

_PeriodDiff could actually extend DateDiff.._

**Comment by stevelacey** [comment]
@eigan can you resolve these conflicts and I'll merge? 🙆‍♂️

**Comment by eigan** [comment]
I will take a look this weekend :)

**Comment by eigan** [comment]
> I will take a look this weekend :)

_- 1 dec 2017_

:walking_man: 

Rebased with latest `master` now.

**Pull request merged**
