### PR TITLE
TIME_TO_SEC for MySQL

### PR DESCRIPTION
**Pull request by pelex**
Added TIME_TO_SEC() function for MySQL

### CODE REVIEW

**Comment by stevelacey** [comment]
Thanks for your contribution! Master has moved ahead since you wrote this and there are now conflicts, can you rebase and I'll get this merged in.

```
git rebase master
git push -f
```

:smile:

**Comment by pelex** [comment]
Now it should be OK.

**Comment by stevelacey** [comment]
Sorry, this needs rebasing again 😞  if you @ me when it's done I'll make sure to merge it.

**Comment by pelex** [comment]
This list of functions in README.md must be defined line by line somehow. Then it will not conflict all the pull requests.

**Comment by stevelacey** [comment]
@pelex yes, or maybe abandon the idea entirely – I would love a PR making this less painful

**Comment by stevelacey** [comment]
@pelex anyway, thanks for your contribution :smile:

**Pull request merged**
