### PR TITLE
Added Mysql PASSWORD function.

### PR DESCRIPTION
**Pull request by ricocrivelli**
I have added Mysql PASSWORD function to my fork.

### CODE REVIEW

**Comment by stevelacey** [comment]
@ricocrivelli looks good, any chance of a test? :smile:

**Comment by SylvainSimon** [comment]
Hey, this function is a good idea !
What happened on this ? @stevelacey can you merge it on project ?
If no, what solution exist for this function in my project ?

**Comment by stevelacey** [comment]
@ricocrivelli @SylvainSimon above changes still required

**Comment by stevelacey** [comment]
Inactive, closing

**Pull request closed without merging**
