### PR TITLE
Add polygon type to Berberlei MySQL Types

### PR DESCRIPTION
**Pull request by roroxide**
I needed doctrine to support polygon type for mysql, but this type does not implemented here.
So, I wrote the PolygonType to be more complete.

### CODE REVIEW

**Comment by stevelacey** [comment]
@roroxide I don't follow what this achieves – I think maybe you wanted to add something into https://github.com/beberlei/DoctrineExtensions/tree/master/src/Query/Mysql? the `DoctrineExtensions\Types` namespace is for coercing database values into alternative PHP objects e.g. custom date libraries such as Carbon. It doesn't look like this is what you're doing here, I'm not sure what you're doing?

**Comment by roroxide** [comment]
I want Polygon Type support by Doctrine directly . It could not be in DBAL project because only mysql supports Polygon . Do you have any idea ?

**Comment by stevelacey** [comment]
@roroxide I think you want to put something in `DoctrineExtensions\Query\Mysql` instead

**Comment by stof** [comment]
@stevelacey PolygonType is a custom type, not a DQL function. so it should not be in the ``Query`` namespace

**Comment by stevelacey** [comment]
@roroxide @stof I don't follow what this is, how its used, or why it's needed – but do enlighten me :grin:

**Comment by nitso** [comment]
Why don't you introduce `Types\Mysql` namespace?

**Comment by poneymagique** [comment]
@stevelacey hello, look at the doc https://dev.mysql.com/doc/refman/5.7/en/spatial-datatypes.html, I know that geometry and point can be used for distances beetwing mysql coordinates, geometry is maybe something like that, it's in the same mysql package. it can be usefull when you want to calculate distance from cities or else.

**Comment by stevelacey** [comment]
I am just going to merge this given @stof seemed happy with it and I don't like throwing away contributions 👌

**Comment by GenisDiaz** [comment]
Is there some doc to use this? I don't know how inject in the config and how can I use it.

**Comment by nitso** [comment]
@GenisDiaz you can use `POLYGON` function in DQL queries according to changes made with PR.

**Pull request merged**
