### PR TITLE
Added MySQL SUBSTRING function. Fixed unit-tests.

### PR DESCRIPTION
**Pull request by ivan-petrunko**
Added MySQL SUBSTRING function. Fixed unit-tests.

### CODE REVIEW

**Comment by stevelacey** [comment]
@ivan-petrunko substring looks good, but what do these new `b`/`blank` aliases that you’ve added achieve? Are these changes necessary?

**Comment by ivan-petrunko** [comment]
@stevelacey, Probably yes. Unit-tests are being crashed with Syntax error if I'm running it without table aliases. So I'd fixed that issue.

**Comment by stevelacey** [comment]
Can you replicate the error on master and paste the message?

**Comment by stevelacey** [comment]
Along with your doctrine version

**Comment by ivan-petrunko** [comment]
@stevelacey,
Doctrine version from composer.lock file:
```
            "name": "doctrine/orm",
            "version": "v2.6.1",
```

I run unit-tests:
```
$ vendor/bin/phpunit
PHPUnit 4.8.36 by Sebastian Bergmann and contributors.

..E.............................................................. 65 / 93 ( 69%)
............................

Time: 1.62 seconds, Memory: 18.00MB

There was 1 error:

1) DoctrineExtensions\Tests\Query\Mysql\BitCountTest::testBitCount
Doctrine\ORM\Query\QueryException: [Syntax Error] line 0, col -1: Error: Expected Doctrine\ORM\Query\Lexer::T_IDENTIFIER, got end of string.

/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:54
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:456
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:324
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:943
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:1741
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:1584
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:1319
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:878
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:847
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:260
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:359
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php:283
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php:207
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/tests/Query/Mysql/BitCountTest.php:13

Caused by
Doctrine\ORM\Query\QueryException: SELECT BIT_COUNT(2) from DoctrineExtensions\Tests\Entities\Blank

/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:43
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:456
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:324
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:943
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:1741
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:1584
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:1319
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:878
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:847
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:260
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:359
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php:283
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php:207
/home/petrunko/www/github/ivan-petrunko/DoctrineExtensions/tests/Query/Mysql/BitCountTest.php:13

FAILURES!
Tests: 93, Assertions: 126, Errors: 1.
```

**Comment by stevelacey** [comment]
@ivan-petrunko seems like it's an issue introduced by Doctrine 2.6, thanks for the fixes! 😀

**Comment by stevelacey** [comment]
@ivan-petrunko I actually just removed your SUBSTRING function – (but held onto your tests and Doctrine 2.6 fixes thanks!) – SUBSTRING is natively supported by Doctrine, maybe you missed it, you can see how to use in the tests you added, I've made some tweaks

https://github.com/beberlei/DoctrineExtensions/blob/master/tests/Query/Mysql/StringTest.php#L73-L107

The only different between yours and the native version – is that Doctrine always opts to use the alias function `SUBSTR` in MySQL – it's an alias, does the same thing, and when you provide only 2 arguments, Doctrine will inject a third specifying the max length as the LENGTH result of the field – other than that it's the same

**Pull request merged**
