### PR TITLE
Fixed tests

### PR DESCRIPTION
**Pull request by stevelacey**

### CODE REVIEW

**Comment by webdevilopers** [comment]
Should we add tests for every function e.g. `GROUP_CONCAT`
https://github.com/beberlei/DoctrineExtensions/pull/111
into
https://github.com/beberlei/DoctrineExtensions/tree/master/tests/DoctrineExtensions/Query
?

**Comment by stevelacey** [comment]
@webdevilopers yes, absolutely, and I would love help adding that. I mused when looking through the tests to discover the only functionality anyone cares about (the query extensions), is wholly untested.

**Comment by stevelacey** [comment]
@webdevilopers a lot of the simpler functions could probably be covered by a generic test thrashing out them all, but the more complex functions with multiple arguments could use a dedicated test case that exercise their various permutation, e.g. when supplying optional arguments.

**Comment by webdevilopers** [comment]
But the "only" thing we can test is the expected `SQL` string, right?
Or should we add `DataFixtures`, `Mock Objects` etc. and go even deeper?

Should we add a new File per Extension or use the existing files that simply batch-tests multiple extensions?
OMG, the `MysqlUdfTest.php` file has its private Entity:
https://github.com/beberlei/DoctrineExtensions/blob/master/tests/DoctrineExtensions/Query/MysqlUdfTest.php#L90-107
;)

**Comment by stevelacey** [comment]
I would be happy with testing the expected SQL for now, we can and do set up entities and a sqllite db in memory to test read/write to and from types such as `Zend_Date`, and soon `Carbon` datetime's – but for query functions it seems like overkill.

I wouldn't be apposed to a separate file per function but it feel like overkill for a lot of them. To me, I think it would make sense to bulk test ones that expect similar arguments – and help encourage they follow the same syntax – i.e. a file to test all functions that accept a single simple arithmetic argument, string, etc, and then separate cases for more complex functions.

**Comment by webdevilopers** [comment]
We could start with the complex ones e.g. `GROUP_CONCAT` and others and then see what's left. I guess the remaining ones are mostly STRING functions. We could categorize them the way the MySQL docs does it: string functions, date functions. These categories become the new Testfiles.

**Comment by stevelacey** [comment]
Yep sounds good

**Comment by webdevilopers** [comment]
I'll be on vacation soon and back at the end of the month. Then I could add the tests.
Do you have any schedule for the *0.3* release?

**Pull request merged**
