### PR TITLE
Add MySQL DAYOFYEAR() function

### PR DESCRIPTION
**Pull request by BenMorel**
http://dev.mysql.com/doc/refman/en/date-and-time-functions.html#function_dayofyear

### CODE REVIEW

**Comment by stevelacey** [comment]
thanks for your contribution :smile:
Thanks for your contribution! Master has moved ahead since you wrote this and there are now conflicts, can you rebase and I'll get this merged in.

```
git rebase master
git push -f
```

:smile:

**Comment by BenMorel** [comment]
@stevelacey done :+1:

**Comment by stevelacey** [comment]
thanks for your contribution :smile:

**Comment by holtkamp** [comment]
@stevelacey any prediction when this lands in a tagged version?

**Comment by holtkamp** [comment]
great ```1.0.10``` it is, thanks!

https://github.com/beberlei/DoctrineExtensions/blob/v1.0.10/src/Query/Mysql/DayOfYear.php

**Pull request merged**
