### PR TITLE
Add MySql LPAD() and RPAD() functions

### PR DESCRIPTION
**Pull request by giuliaries**
Added MySql LPAD() function

### CODE REVIEW

**Comment by stevelacey** [comment]
Can you resolve the conflicts and I'll get this merged, thanks!

**Comment by giuliaries** [comment]
Thank you for your reply.
I resolved two conflicts that I've found, but the Travis doesn't start so I don't know if I miss some other conflict... Where I can see it?

**Comment by stevelacey** [comment]
The branch still appears to conflict, I guess that is the reason?

**Comment by stevelacey** [comment]
Could you rebase the lot anyway? Ideally this should be one commit

**Comment by giuliaries** [comment]
Uhm... you mean all my seven commit in one? How can I rebase? Excuse me but I never do this from GitHub...

**Comment by stevelacey** [comment]
If you run an interactive rebase back to the commit before your first commit like so:

```
git rebase -i 0e7b466^
```

git will say:

```
pick 0e7b466 Added MySql LPAD() function
pick 3264938 Fixed MySql LPAD() function
pick 2e74dba Fixed MySql LPAD() test
pick a7b0943 Fixed MySql LPAD() test
pick 28b8094 Added MySql RPAD() function
pick eb945a1 Resolve a conflict
pick cb16696 Resolve a conflict on README
```

You can change all of the subsequent commits to `squash` or `s`:

```
p 0e7b466 Added MySql LPAD() function
s 3264938 Fixed MySql LPAD() function
s 2e74dba Fixed MySql LPAD() test
s a7b0943 Fixed MySql LPAD() test
s 28b8094 Added MySql RPAD() function
s eb945a1 Resolve a conflict
s cb16696 Resolve a conflict on README
```

and then tidy up the commit message (it'll merge the 7 messages into 1) `Added LDAP & RPAD functions`

You'll end up in this state:

```
On branch master
Your branch and 'origin/master' have diverged,
and have 1 and 7 different commits each, respectively.
```

You can then force push that over your branch (it's non-fastforward so will need force) `git push -f` and you'll have 1 commit for your changes.

**Comment by giuliaries** [comment]
Thank you so much for your reply! I done the rebase, I hope it is right.
Anyway the branch is still in conflict, but I don't know why, at the beginning the branch was not in conflict...

**Comment by stevelacey** [comment]
Yes I knew that would happen but I thought I'd see if you got this far first ;) it's because your branch is 1 commit ahead and a few commits behind beberlei/DoctrineExtensions master branch – actually I think somehow part of your branch got rewritten... normally you'd just rebase against beberlei master at this point... maybe the rebase I advised you to do was not quite right, I think it has rewritten the most recent commit before your work starts, which means it can't be merged cleanly.

I think the easiest thing to do now is soft reset your change, stash, pull the tip of beberlei master, stash pop, resolve the conflict in README.md, do a new commit and finally force push.

Isn't git fun :grinning: anyway, it'd be something like this:

```sh
git clone https://github.com/giuliaries/DoctrineExtensions.git
cd DoctrineExtensions
git remote add b https://github.com/beberlei/DoctrineExtensions.git
git fetch b
git reset --soft HEAD^
git stash
git pull b master
git stash pop
** resolve README conflict **
git add README.md
git commit -m "Added LDAP & RPAD functions"
git push -f
```

This should result in a pull request that would merge and I expect Travis will then test it. Any questions just ask.

**Comment by giuliaries** [comment]
OK, I'm happy because I have notice that there was other commits after mine. I tried to fix the README but in the wrong way.

Yeah, Git isn't fun, but for me, not for you :P 
Generally I use the basic commands, I have to do practice with more commands!

Thank you so much for you teaching :)

Is now the code ok? There are no conflicts but Travis doesn't start yet...

**Comment by stevelacey** [comment]
What is wrong with the way you fixed the README? Looks fine to me.

This looks great, thanks for tidying it up – hope you learnt something! I was being sarcastic about Git being fun :wink:

**Comment by stevelacey** [comment]
Oh and yeah, I have no idea what problem Travis has with this PR but I am happy to merge now.

**Comment by giuliaries** [comment]
Thank you so much :D 

I was referring to the README before the last edit.
Yeah, I learned new things but I have to study more! Thank you again!

**Pull request merged**
