### PR TITLE
Add PHP 8.2 compatibility

### PR DESCRIPTION
**Pull request by javer**
See https://github.com/javer/DoctrineExtensions/actions/runs/3695002856 for successful GitHub Actions run.

### CODE REVIEW

**Comment by Chris53897** [comment]
It would be great to have full php 8.2 support.
I am not sure if this PR should upgrade actions/checkout@v3 and actions/cache@v3 to get rid of deprecation messages.
Otherwise a seperate PR with only CI changes could be opened.

**Comment by javer** [comment]
Hi! Do you have any plans to merge PR this year?

**Comment by Chris53897** [comment]
@javer Please see https://github.com/beberlei/DoctrineExtensions/pull/380#issuecomment-1162899265

**Comment by cbeyer** [comment]
+1, waiting for new release. Thanks!

**Pull request merged**
